infinispan:
  clusterName: infinispan
endpoints:
  hotrod:
    enabled: true
    qup: auth
    serverName: infinispan
  memcached:
    enabled: false
  rest:
    enabled: true
jgroups:
  transport: udp
keystore:
  alias: server