name: Release Images

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The infinispan-images branch to checkout when cutting the release."
        required: true
        default: "main"
      ispnVersion:
        description: 'Version of Infinispan artifacts to be used'
        required: true
        type: string
      images:
        description: 'A comma-separated list of images to be released'
        default: 'server, server-native, cli'
        type: string
      latest:
        description: 'If true, updates the :latest tag to equal this release for each selected image'
        default: true
        type: boolean
      push:
        description: 'If false, we skip pushing the image to remote repositories'
        default: true
        type: boolean
    outputs:
      artifact:
        description: The name of the uploaded image artifact
        value: ${{ jobs.build.outputs.artifact }}

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs:
      image-matrix: ${{ steps.images.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - id: images
        run: |
          IMAGES=$(echo ${{ inputs.images }} | sed -n 's/server/server-openjdk/p')
          echo "matrix=$(echo ${IMAGES}  | jq -Rc 'split(", ")')" >> $GITHUB_OUTPUT

  release:
    needs: [meta]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        descriptor: ${{ fromJson(needs.meta.outputs.image-matrix) }}
    env:
      IMAGE: ${{ matrix.descriptor == 'server-openjdk' && 'server' || matrix.descriptor }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install CEKit
        uses: cekit/actions-setup-cekit@v1.1.5

      - uses: chrisdickinson/setup-yq@latest

      - name: Update Descriptor Versions
        run: ./.github/scripts/update_image_descriptors.sh >> $GITHUB_ENV
        env:
          ISPN_VERSION: ${{ inputs. ispnVersion }}
          DESCRIPTOR: ${{ matrix.descriptor }}

      - name: Create Dockerfile
        run: |
          cekit -v --descriptor ${{ matrix.descriptor }}.yaml build --overrides "{\"version\": \"$TAG\"}" --dry-run docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          file: target/image/Dockerfile
          tags: |
            quay.io:infinispan/:${{ env.IMAGE }}:${{ inputs.imageTag }}
            registry.hub.docker.com:infinispan/${{ env.IMAGE }}:${{ inputs.imageTag }}

      - name: Commit changes and create tag
        run: |
          set -x # TODO remove
          git config user.email "infinispan@infinispan.org"
          git config user.name "Infinispan"
          git add ${{ matrix.descriptor }}.yaml
          git commit -m 'Releasing Version ${IMAGE_VERSION} of ${IMAGE} image'"
          git tag ${IMAGE_VERSION}

      - name: Push Git changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ inputs.branch }}
          tags: true
